### ISSUE TITLE
How to connect ethereum chain with tendermint chain through ibc?

### ISSUE THREAD

**Issue by yaziciahmet** [datachainlab/yui-relayer-build#10]
My attempt is as follows:
1. Build docker images with the Makefile residing inside chains/ethereum and chains/tendermint
2. Run tendermint-chain0 and ethereum-ganache1 images through docker-compose
3. Copy tendermint mnemonic from the container to local
4. Initialize relayer config:
```bash
${RLY} config init
${RLY} chains add-dir configs/demo/
```
Config file for tendermint chain (configs/demo/ibc-0.json):
```
{
  "chain": {
    "@type": "/relayer.chains.tendermint.config.ChainConfig",
    "key": "testkey",
    "chain_id": "ibc0",
    "rpc_addr": "http://localhost:26657",
    "account_prefix": "cosmos",
    "gas_adjustment": 1.5,
    "gas_prices": "0.025stake"
  },
  "prover": {
    "@type": "/relayer.chains.tendermint.config.ProverConfig",
    "trusting_period": "336h"
  }
}
```
Config file for ethereum chain (configs/demo/ibc-1.json):
```
{
  "chain": {
    "@type": "/relayer.chains.ethereum.config.ChainConfig",
    "chain_id": "ibc1",
    "eth_chain_id": 2019,
    "rpc_addr": "http://localhost:8745",
    "hdw_mnemonic": "math razor capable expose worth grape metal sunset metal sudden usage scheme",
    "hdw_path": "m/44'/60'/0'/0/0",
    "ibc_address": "0x702E40245797c5a2108A566b3CE2Bf14Bc6aF841"
  },
  "prover": {
    "@type": "/relayer.provers.mock.config.ProverConfig"
  }
}
```
5. Setup key for tendermint client (extracts mnemonic from the json file copied to local from the container, and restores key):
```bash
SEED0=$(jq -r '.mnemonic' < ${FIXTURES_DIR}/tendermint/ibc0/key_seed.json)
echo "Key $(${RLY} tendermint keys restore ibc0 testkey "$SEED0") imported from ibc0 to relayer..."
```
6. Initialize tendermint light client, and add a path between two chains. Here is the path configuration file:
```json
{
  "src": {
    "chain-id": "ibc0",
    "client-id": "mock-client-0",
    "connection-id": "connection-0",
    "channel-id": "channel-0",
    "port-id": "transfer",
    "order": "unordered",
    "version": "transfer-1"
  },
  "dst": {
    "chain-id": "ibc1",
    "client-id": "mock-client-0",
    "connection-id": "connection-0",
    "channel-id": "channel-0",
    "port-id": "transfer",
    "order": "unordered",
    "version": "transfer-1"
  },
  "strategy": {
    "type": "naive"
  }
}
```
7. Run tx clients, connection, and channel:
```bash
retry 5 $RLY tx clients $PATH_NAME
retry 5 $RLY tx connection $PATH_NAME
retry 5 $RLY tx channel $PATH_NAME
```

Here, tx clients command throws this output with error:
```
I[2023-05-16|22:30:31.615] - [ibc0] -> sending transaction:             
{"client_state":{"@type":"/ibc.lightclients.mock.v1.ClientState","latest_height":{"revision_number":"0","revision_height":"17"}},"consensus_state":{"@type":"/ibc.lightclients.mock.v1.ConsensusState","timestamp":"1684265431511071182"},"signer":"cosmos1f77addquzj5yhuga8mhquu49ghpuzejxztjnd9"}
E[2023-05-16|22:30:31.615] - [ibc0] -> err(rpc error: code = InvalidArgument desc = unable to resolve type URL /ibc.lightclients.mock.v1.ClientState: tx parse error: invalid request) 
2023/05/16 22:30:31 ethereum: failed to send: VM Exception while processing transaction: revert
```

And tx connection fails after 5 retry.

I would appreciate any guidance/help on this regard.

**Comment by yaziciahmet** [comment]
My bad. Didn't realize v0.3 does not support eth to tm yet.

**Comment by bluele** [comment]
@yaziciahmet  Thank you for opening the issue.

This is due to a mock-client's issue: https://github.com/datachainlab/ibc-mock-client/issues/7

The upcoming v0.4 (w/ibc-go v7) release will include this fix.

**Comment by yaziciahmet** [comment]
@bluele May I ask whether bridging tendermint to ethereum is possible at the moment with v0.2? The bridge is running in the sense that I can setup the bridge with the scriptstests/cases/eth2tm, but there are no test scripts for me to see that it actually works. I have tried `./build/yrly tx transfer ibc01 ibc0 ibc1 100samoleans cosmos1u8gysmehvrf74astdg6dsxx3psrfpe8va8jq0a`. Here ibc0 is the tendermint chain and ibc1 is the ethereum chain. But ethereum client reverts with VM Exception and the packet is not relayed.

One thing which confuses me in the above command is that, even though ibc1 is ethereum chain, it still expects bech32 formatted address. I would assume bech32 addresses are convertable to hex addresses in a 1-to-1 fashion, am I right?

**Comment by bluele** [comment]
> But ethereum chain reverts with VM Exception.

I think it is caused by the encoding mismatch between the ics-20 impl of ibc-go and ibc-solidity. A related issue is here: https://github.com/hyperledger-labs/yui-ibc-solidity/issues/81

We have recently developed a mock app(just echo the packet data) for relay between tendermint and ethereum. It also can be released soon.

> And lastly is there an estimate about the release date of the v0.4?

optimistically, in the next month.

**Comment by yaziciahmet** [comment]
Oh, then I would assume it should be fine for some other ibc-go and ibc-solidity port?

**Comment by yaziciahmet** [comment]
Lastly, may I ask which version are you using for the mock app to relay between tm and eth?

**Comment by bluele** [comment]
The current support is v0.3 (ibc-v4), but v0.4 (ibc-v7) will also be supported.

**Comment by chenqping** [comment]
hi @bluele, May I ask if ibc-solidity supports ethereum ibc, as I found the repo didn't implement light client for ethereum, also I found it used the MockClient, so in true, it didn't support yet?
